spring.application.name=project-common
server.servlet.context-path=/api

# common config shared by services
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreaker-events,prometheus

